apiVersion: apps/v1
kind: Deployment
metadata:
  name: the1-web-deployment
  namespace: the1-web-dev
  labels:
    app: the1-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the1-web
  template:
    metadata:
      labels:
        app: the1-web
    spec:
      containers:
        - image: 826128703544.dkr.ecr.ap-southeast-1.amazonaws.com/the1web:latest
          imagePullPolicy: Always
          name: the1-web
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
        
